---
services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest
    container_name: nebula-sync
    restart: unless-stopped
    env_file: .env
    environment:
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=* * * * *
    - TZ=America/Los_Angeles
    - CLIENT_SKIP_TLS_VERIFICATION=true
